[build]
  command = "npm run build"
  publish = "dist"
  autoCancel = true
  ignore = "git diff --quiet HEAD^ HEAD src/ public/ netlify.toml package.json src/data/produtos.json"

[[edge_functions]]
path = "/produto/*"
function = "og"